version: '2.4'
services:
  dev:
    build:
      context: .
      target: development
    env_file: ./dev/env
    command: npm run watch
    volumes:
      - './src:/opt/project/src'
      - '~/.config/gcloud:/root/.config/gcloud'
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
