---
swagger: '2.0'
info:
  version: 1.0.0
  title: Ingest API
  description: |
    The Ingest API allows third parties to upload vessel datasets to GFW. These
    datasets will eventually be processed by GFW to classify and detect
    fishing, transhipments and other interesting behavior at sea.

    ## Authorization

    This API requires an API key to use. The key should be included in the
    `Authorization` header of all requests to the API.

securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: authorization

definitions:
  ValidationError:
    type: object
    required:
      - param
      - code
      - errors
    properties:
      param:
        title: Parameter
        description: |
          Request parameter which caused a validation error.
        type: string
      code:
        title: Code
        description: |
          Short error code which identifies the kind of validation error that
          was detected.
        type: string
      errors:
        title: Errors
        description: |
          List of validation errors detected in the parameter.
        type: array
        items:
          title: Error
          description: |
            Describes one of the errors detected in the parameter.
          type: object
          required:
            - code
            - message
            - path
          properties:
            code:
              title: Code
              description: |
                Short error code which identifies the kind of validation error that
                was detected.
              type: string
            message:
              title: Message
              description: |
                Short informational message which describes the validation
                error that was detected.
              type: string
            path:
              title: Path
              description: |
                Path to the exact property which caused the error.
              type: array

responses:
  BadRequest:
    description: |
      Bad request.

  Unauthorized:
    description: |
      Unauthorized, either the api key is invalid or expired.

  UnprocessableEntity:
    description: |
      Unprocessable entity. Some of the values are invalid.
    schema:
      $ref: '#/definitions/ValidationError'

paths:
  /v1/ingest:
    post:
      summary: |
        Feeds vessel positional data into the GFW platform.
      description: |
        Feeds vessel positional data into the GFW platform. The data is
        validated and enqueued for later processing.
      tags:
        - Ingestion
      consumes:
        - application/json
      security:
        - apiKey: []
      parameters:
        - name: data
          in: body
          description: |
            The vessel positional data to ingest.
          required: true
          schema:
            type: array
            title: Vessel positional data
            items:
              title: Vessel Position
              type: object
              required:
                - vesselId
                - lat
                - lon
                - timestamp
                - speed
                - course
              properties:
                vesselId:
                  title: Vessel Id
                  description: |
                    Alphanumeric identifier which uniquely identifies the
                    vessel.
                  type: string
                lat:
                  title: Latitude
                  description: Latitude
                  type: number
                  format: float
                  minimum: -90
                  maximum: 90
                lon:
                  title: Longitude
                  description: Longitude
                  type: number
                  format: float
                  minimum: -180
                  maximum: 180
                timestamp:
                  title: Timestamp
                  description: |
                    ISO8601 representation of the date and time this position
                    was detected.
                  type: string
                  format: date-time
                speed:
                  title: Speed
                  description: |
                    Speed the vessel had at the time the position was detected.
                  type: object
                  required:
                    - value
                    - unit
                  properties:
                    value:
                      type: number
                      format: float
                    unit:
                      type: string
                      enum:
                        - knots
                course:
                  title: Course
                  description: |
                    Course the vessel had at the time the position was detected.
                  type: object
                  required:
                    - value
                    - unit
                  properties:
                    value:
                      type: number
                      format: float
                    unit:
                      type: string
                      enum:
                        - degrees
                imo:
                  title: IMO
                  description: |
                    International Maritime Organization number for the vessel.
                  type: string
                shipName:
                  title: Ship Name
                  description: |
                    Name of the ship.
                  type: string
                country:
                  title: ISO3166 country code
                  description: |
                    [ISO3166-1-alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
                    code for the vessel country.
                  type: string
                extra:
                  title: Extra information
                  description: |
                    Extra information about the vessel or the positional
                    characteristics of it not covered in other fields.
                  type: object

      responses:
        "400":
          $ref: '#/responses/BadRequest'
        "401":
          $ref: '#/responses/Unauthorized'
        "422":
          $ref: '#/responses/UnprocessableEntity'
        "200":
          description: |
            Expected response to a successful request.
